version: "3"
services:
 MavenWebAppContainer:
  image: sddocker333/maven-web-application:VERSION
  port:
   - 8080:8080
  volumes:
   - MavenWebAppVol
  networks:
   - MavenWebAppNetwork
volumes:
 MavenWebAppVol:
  - driver: local
networks:
 MavenWebAppNetwork:
  - driver: bridge
