version: "3"
services:
 MavenWebAppContainer:
  image: sddocker333/maven-web-application:VERSION
  ports:
   - 8080:8080
volumes:
 MavenWebAppVol:
  external: true
networks:
 MavenWebAppNetwork:
  external: true
