version: "3"
services:
 MavenWebAppContainer:
  image: sddocker333/maven-web-application:VERSION
  ports:
   - 8080:8080
  volumes:
   - MavenWebAppVol
  networks:
   - MavenWebAppNetwork
volumes:
 MavenWebAppVol:
  external: true
networks:
 MavenWebAppNetwork:
  driver: bridge
